export const dummyInterviews: Interview[] = [
  {
    id: "1",
    userId: "user1",
    role: "Frontend Developer",
    type: "Technical",
    techstack: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    level: "Junior",
    questions: ["What is React?"],
    finalized: false,
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "2",
    userId: "user1",
    role: "Full Stack Developer",
    type: "Mixed",
    techstack: ["Node.js", "Express", "MongoDB", "React"],
    level: "Senior",
    questions: ["What is Node.js?"],
    finalized: false,
    createdAt: "2024-03-14T15:30:00Z",
  },
  {
    id: "3",
    userId: "user2",
    role: "Backend Developer",
    type: "Technical",
    techstack: ["Python", "Django", "PostgreSQL"],
    level: "Mid-Level",
    questions: ["What is Django?"],
    finalized: true,
    createdAt: "2024-03-13T09:45:00Z",
  },
  {
    id: "4",
    userId: "user3",
    role: "Data Scientist",
    type: "Behavioral",
    techstack: ["Python", "R", "SQL"],
    level: "Senior",
    questions: ["Describe a challenging data project you worked on."],
    finalized: true,
    createdAt: "2024-03-12T11:20:00Z",
  }
];
